[programs.localnet]
vibe_market = "VBMLwfUCFZHvsqTzTQKfgdJFQEWuKSVQZVdc9T2SqFf"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "devnet"
wallet = "./devnet-wallet.json"

[scripts]
test = "yarn ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
