[programs.localnet]
vibe_market = "vXXYKPPwmERsfQPKEwhmnQBABVDoLUKRzz5LtLk9ndS"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "mainnet"
wallet = "./mainnet-wallet.json"

[scripts]
test = "yarn ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
