[programs.localnet]
vibe_market = "VBMXoEzW3FuMarn35AjTg8v32md7aPdh6N3EkEG6noL"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "devnet"
wallet = "./devnet-wallet.json"

[scripts]
test = "yarn ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
