[programs.localnet]
vibe_market = "A3RM1Z9JW6JiTNheD4JcjnE9qLGLk9phgv8GfszEyE8L"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "devnet"
wallet = "./devnet-wallet.json"

[scripts]
test = "yarn ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
